==> vim main.yml 
          import_playbook :  labHand.yml  

==>  Vim labHand.yml       
           hosts: all 
           tasks: 
                  - name: install apache ( yum install httpd )             #install file 
                     yum:  name= httpd state=present
                    Notify: 
                          -h1
                   ignore_erorr:  true                                         # if true continue  

                   - name: create  /file (touch file)                       ##create file 
                     file: path=/file.txt   state=touch  

             handlers:     
                       name:    -h1  (systemctl start httpd)                  #start Apache server   
                     service: name= httpd state=started                  

==> ansible-playbook  main.yml

Result : Run  task1 task2 task3
